"""add totp fields to users

Revision ID: 56047a498bfd
Revises: aa16fe1a1e46
Create Date: 2026-09-01 22:09:51.086776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56047a498bfd'
down_revision: Union[str, Sequence[str], None] = 'aa16fe1a1e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: hand-adjusted — autogenerate emitted totp_enabled as NOT NULL
    # with no default, which fails against a table that already has rows
    # (nothing to backfill existing rows with). server_default='0' backfills
    # every existing user to False; the model's own default=False handles
    # all new rows going forward, so the server_default stays permanently
    # rather than being a one-time thing to drop afterward.
    op.add_column('users', sa.Column('totp_secret_encrypted', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret_encrypted')
    # ### end Alembic commands ###
